// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACard: typeof import('@arco-design/web-vue')['Card']
    ACardMeta: typeof import('@arco-design/web-vue')['CardMeta']
    ACarousel: typeof import('@arco-design/web-vue')['Carousel']
    ACarouselItem: typeof import('@arco-design/web-vue')['CarouselItem']
    ACol: typeof import('@arco-design/web-vue')['Col']
    AForm: typeof import('@arco-design/web-vue')['Form']
    AFormItem: typeof import('@arco-design/web-vue')['FormItem']
    AImage: typeof import('@arco-design/web-vue')['Image']
    AInput: typeof import('@arco-design/web-vue')['Input']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    ARow: typeof import('@arco-design/web-vue')['Row']
    Article: typeof import('./src/views/article/index.vue')['default']
    ArticleListImg: typeof import('./src/components/layout/ArticleListImg.vue')['default']
    ArticleListInfo: typeof import('./src/components/layout/ArticleListInfo.vue')['default']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    ATypographyParagraph: typeof import('@arco-design/web-vue')['TypographyParagraph']
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText']
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle']
    Classification: typeof import('./src/views/classification/index.vue')['default']
    Comment: typeof import('./src/components/layout/Comment.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Friend: typeof import('./src/views/friend/index.vue')['default']
    Home: typeof import('./src/views/home/index.vue')['default']
    Login: typeof import('./src/views/login/index.vue')['default']
    MdEdtior: typeof import('./src/components/md-edtior/index.vue')['default']
    Message: typeof import('./src/components/layout/Message.vue')['default']
    Picture: typeof import('./src/views/picture/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/icons/SvgIcon.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
    User: typeof import('./src/views/user/index.vue')['default']
  }
}
