// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAffix: typeof import('@arco-design/web-vue')['Affix']
    AButton: typeof import('@arco-design/web-vue')['Button']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    App: typeof import('./src/views/home/App.vue')['default']
    ArticleList: typeof import('./src/components/layout/ArticleListImg.vue')['default']
    ArticleListImg: typeof import('./src/components/layout/ArticleListImg.vue')['default']
    ArticleListInfo: typeof import('./src/components/layout/ArticleListInfo.vue')['default']
    ASpace: typeof import('@arco-design/web-vue')['Space']
    Home: typeof import('./src/views/home/Home.vue')['default']
    SvgIcon: typeof import('./src/components/icons/SvgIcon.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
  }
}
