// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AAffix: typeof import('@arco-design/web-vue')['Affix']
    AAnchor: typeof import('@arco-design/web-vue')['Anchor']
    AAnchorLink: typeof import('@arco-design/web-vue')['AnchorLink']
    AAvatar: typeof import('@arco-design/web-vue')['Avatar']
    ABackTop: typeof import('@arco-design/web-vue')['BackTop']
    AButton: typeof import('@arco-design/web-vue')['Button']
    ACarousel: typeof import('@arco-design/web-vue')['Carousel']
    ACarouselItem: typeof import('@arco-design/web-vue')['CarouselItem']
    ACol: typeof import('@arco-design/web-vue')['Col']
    ADrawer: typeof import('@arco-design/web-vue')['Drawer']
    AImage: typeof import('@arco-design/web-vue')['Image']
    AImg: typeof import('@arco-design/web-vue')['Img']
    AImge: typeof import('@arco-design/web-vue')['Imge']
    ALayout: typeof import('@arco-design/web-vue')['Layout']
    ALayoutContent: typeof import('@arco-design/web-vue')['LayoutContent']
    ALayoutFooter: typeof import('@arco-design/web-vue')['LayoutFooter']
    ALayoutHeader: typeof import('@arco-design/web-vue')['LayoutHeader']
    AMenu: typeof import('@arco-design/web-vue')['Menu']
    AMenuItem: typeof import('@arco-design/web-vue')['MenuItem']
    ARadio: typeof import('@arco-design/web-vue')['Radio']
    ARadioGroup: typeof import('@arco-design/web-vue')['RadioGroup']
    ARow: typeof import('@arco-design/web-vue')['Row']
    ArticleListImg: typeof import('./src/components/layout/ArticleListImg.vue')['default']
    ArticleListInfo: typeof import('./src/components/layout/ArticleListInfo.vue')['default']
    ARwo: typeof import('@arco-design/web-vue')['Rwo']
    ASubMenu: typeof import('@arco-design/web-vue')['SubMenu']
    'ASubMenu-': typeof import('@arco-design/web-vue')['SubMenu-']
    ASubMenuItem: typeof import('@arco-design/web-vue')['SubMenuItem']
    ATypographyParagraph: typeof import('@arco-design/web-vue')['TypographyParagraph']
    ATypographyText: typeof import('@arco-design/web-vue')['TypographyText']
    ATypographyTit: typeof import('@arco-design/web-vue')['TypographyTit']
    ATypographyTitle: typeof import('@arco-design/web-vue')['TypographyTitle']
    Classification: typeof import('./src/views/classification/index.vue')['default']
    Classify: typeof import('./src/views/classify/index.vue')['default']
    Footer: typeof import('./src/components/layout/Footer.vue')['default']
    Home: typeof import('./src/views/home/index.vue')['default']
    index: typeof import('./src/views/home/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./src/components/icons/SvgIcon.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
    User: typeof import('./src/views/user/index.vue')['default']
  }
}
